### ISSUE TITLE
Current call doesn't seem to have the planutils planners accessible

### ISSUE THREAD

**Issue by haz** [AI-Planning/planning-as-a-service#11]
This is the line making the call: https://github.com/AI-Planning/planning-as-a-service/blob/master/server/celery-queue/tasks.py#L35

Seems to work if you attach to the worker docker image and run a similar line. Note that `executable='/bin/bash'` is used in order to get the `.bashrc` sourced, which adds the right directory to the `PATH` variable. Perhaps there is a UID mismatch between running attached to the image -vs- the server code handling the requests.

**Comment by camcunningham** [comment]
Think this might fix it, check it out @haz 

https://github.com/AI-Planning/planning-as-a-service/tree/planutils-functionality

**Comment by haz** [comment]
Pretty sure this is resolved.
