### ISSUE TITLE
Planning result return with HTTP response

### ISSUE THREAD

**Issue by JamieYuu** [AI-Planning/planning-as-a-service#14]
Currently, the planning-as-a-service program will store the PDDL plan files to the local directory (According to the deployment record: https://drive.google.com/file/d/1El1v53_h5BlfT0K3PaCIgr_oBSmPRpbT/view?usp=sharing)

The HTTP response only returns the status of the solving process, it would be great to allow the plan results return within the HTTP response, so that users can get the plan result by sending requests through the URL.

**Comment by camcunningham** [comment]
Going to take a stab at this

**Comment by jan-dolejsi** [comment]
What do you mean by _Planning result_? The plans? Or metrics of the plan? Or stats from the search?

Plans are (obviously) getting returned already.

**Comment by haz** [comment]
I believe that the original request was for a synchronous return. We've obviously long since moved away from that model, and polling is the current solution (to be superseded by #40 or similar). Will close for now, but feel free to re-open, @JamieYuu , if I've gotten it wrong.
