### ISSUE TITLE
use error : no job control in this shell\n/root/.planutils/packages/downward/run: line 3:    26 Segmentation fault      singularity run -e $

### ISSUE THREAD

**Issue by kk-Aye** [AI-Planning/planning-as-a-service#45]
I use VM about Ubuntu20 and docker build method. After i make it successfully, i try to solve PDDL in vscode, but it report this error. I do not understand why this is.

**Comment by haz** [comment]
Are you running the docker in `--privileged` mode?

**Comment by kk-Aye** [comment]
> Are you running the docker in `--privileged` mode?
I find the setting of privileged mode in docker-compose.yml and it was set as true. And i have no extra configuration.

**Comment by kk-Aye** [comment]
> Are you running the docker in `--privileged` mode?

I check the modes of the four docker containers running using the [docker inspect --format='{{.hostconfig.privileged}}'] command, where server_web_1 and server_worker_1 are true. server_monitor_1 and server_redis_1 are false.

**Comment by haz** [comment]
Hrmz...must be something else internally. I'd suggest perhaps running the planutils lightweight server instead: https://github.com/AI-Planning/planutils/tree/main/environments/server

**Comment by kk-Aye** [comment]
> 

Thank you, I will try.

**Comment by kk-Aye** [comment]
> Hrmz...must be something else internally. I'd suggest perhaps running the planutils lightweight server instead: https://github.com/AI-Planning/planutils/tree/main/environments/server

I'm sorry, after i installed the planutils lightweight server, I don't know how can i use it (/(ㄒoㄒ)/~~). I cant't find the bash file for lama or other solver in my host machine, can it only be used in docker?

**Comment by haz** [comment]
The server script is set up that way, ya. You don't have access to docker to run it?

**Comment by kk-Aye** [comment]
> The server script is set up that way, ya. You don't have access to docker to run it?

No, I‘m sorry i didn't make that clear. docker service is running, but i want to use vscode'PDDL plugin, Using 'localhost:5001/package/optic/solve' as planning engine but it failed and prompt "socket hang up". 

![image](https://user-images.githubusercontent.com/64071525/227430053-b5a897a3-8da6-4127-8880-12f036c70803.png)
![image](https://user-images.githubusercontent.com/64071525/227430166-ddb58fdb-e66b-4d1e-85d1-891d66024224.png)

**Comment by haz** [comment]
Can you post what the browser shows for `localhost:5001/packages` and `localhost:5001/package/optic`?

**Comment by haz** [comment]
If heading to those URL's is giving nothing, then the server isn't even accessible. Either not running properly, or network issues as you hypothesized. My money's on the network config for your machine too ;).

**Comment by kk-Aye** [comment]
> If heading to those URL's is giving nothing, then the server isn't even accessible. Either not running properly, or network issues as you hypothesized. My money's on the network config for your machine too ;).

Thank you for your suggestion, but I‘m sorry, I don't understand what you mean by the last sentence. Why? X﹏X

**Comment by haz** [comment]
> I don't understand what you mean by the last sentence. Why?

Oh, just meant that my first hunch would be something funny going on with the port mapping (it's usually what breaks first when running servers via docker).

**Comment by haz** [comment]
Any update on this, @kk-Aye ?

**Comment by kk-Aye** [comment]
> Any update on this, @kk-Aye ?

I'm sorry. I'm busy writing papers and exams afterwards. Virtual machine configuration is not progressing. I will continue the configuration under the virtual machine after the paper is passed. If you need, I can close this issue, and then I will open the issue when I make some progress.

**Comment by haz** [comment]
Ya, let's close for now -- we're in the midst of launching the webserver equivalent (being demo'd at the ICAPS conference this summer), so that might make the issue a non-starter anyway. Hope the exams go well!
