### ISSUE TITLE
Incorrect plan output

### ISSUE THREAD

**Issue by chillray** [AI-Planning/planning-as-a-service#55]
**Describe the Bug:**
In the Floortile domain, there are only two available colors: black and white. However, the planning output incorrectly includes black2 in the precondition and effect of an action, which is not a defined color in the domain specifications.
<img width="407" alt="image" src="https://github.com/AI-Planning/planning-as-a-service/assets/52360130/ca0b26c8-b358-4e21-ba58-ab17a8984457">

<img width="391" alt="image" src="https://github.com/AI-Planning/planning-as-a-service/assets/52360130/7f777976-b524-480d-a334-3e276dc43e03">

**To Reproduce:** 
[https://editor.planning.domains/#read_session=enUY7oRSpJ](url)
Use BWFS to solve the problem

**Expected Behavior:**
The plan should only include the colors "black" and "white" as these are the only two defined in the domain.

**Observed Behavior:**
The action in the generated plan mistakenly includes black2 in its precondition and effect, suggesting an error in the planning editor adaptor.

**Comment by haz** [comment]
Which problem ID is this from?

**Comment by chillray** [comment]
> Which problem ID is this from?

[https://editor.planning.domains/#read_session=enUY7oRSpJ](url)Sorry for the wrong link, just updated the reproduce session link. The problem id is P01-4-3-2.
