### ISSUE TITLE
Setting up new PAAS, Delfi fails to install

### ISSUE THREAD

**Issue by rpgoldman** [AI-Planning/planning-as-a-service#57]
I'm afraid I couldn't make much out of the following error message:

```
=> ERROR [4/8] RUN planutils install -f -y delfi                                                                             1.7s
------
 > [4/8] RUN planutils install -f -y delfi:
1.391 FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://ctpelok77/delfi-deploy: no response received from singularity hub
1.404 rm: cannot remove 'delfi.sif': No such file or directory
1.405 delfi will be installed.
1.405
1.405 About to install the following packages: delfi (652M)
1.405 Installing delfi...
1.405
1.405 Error installing delfi. Rolling back changes...
------
Dockerfile:12
--------------------
  10 |
  11 |     #Optimal classical planning
  12 | >>> RUN planutils install -f -y delfi
  13 |
  14 |     # top-k classical planning
--------------------
ERROR: failed to solve: process "/bin/sh -c planutils install -f -y delfi" did not complete successfully: exit code: 1
make: *** [Makefile:4: build-planutils-image] Error 1
```

Not critical for me: I can do without Delfi for the foreseeable future, but figured I should pass this on.

**Comment by rpgoldman** [comment]
forbiditerative-topk failed for me with the same kind of error -- any chance these are issues with @ctpelok77 's images in particular? No idea why that would be, but I see Michael's username in both locations.

**Comment by rpgoldman** [comment]
Nope. `enhsp` failed, too.

These are the ones that worked and didn't, from the `Dockerfile`:
```
# FD Planner
RUN planutils install -f -y lama-first -- SUCCEEDED

# Satisficing classical planning
RUN planutils install -f -y dual-bfws-ffparser -- SUCCEEDED

#Optimal classical planning
# RUN planutils install -f -y delfi  -- FAILED

# top-k classical planning
# RUN planutils install -f -y forbiditerative-topk -- FAILED

# numeric planning
# RUN planutils install -f -y enhsp-2020 -- FAILED

# PDDL3 support
RUN planutils install -f -y optic -- SUCCEEDED

# Temporal planning
RUN planutils install -f -y tfd -- SUCCEEDED
```

**Comment by haz** [comment]
Aye, it looks like we've lost singularity hub. These are the packages impacted:

```bash
cerberus/install:singularity pull --name cerberus.sif shub://ctpelok77/fd-red-black-postipc2018
delfi/install:singularity pull --name delfi.sif shub://ctpelok77/delfi-deploy
enhsp-2018/install:singularity pull --name enhsp-2018.sif shub://enricos83/enhsp:2018
enhsp-2019/install:singularity pull --name enhsp-2019.sif shub://enricos83/enhsp:2019
enhsp-2020/install:singularity pull --name enhsp-2020.sif shub://enricos83/enhsp:2020
forbiditerative/install:singularity pull --name forbiditerative.sif shub://ctpelok77/fi-singularity
kstar/install:singularity pull --name kstar.sif shub://ctpelok77/kstar
```

@ctpelok77 @hstairs : Looks like it's all down to you two. Any chance we can get a PR that updates the target pull? Either via Dockerhub (e.g., [enhsp](https://github.com/AI-Planning/planutils/blob/main/planutils/packages/enhsp/install)) or GitHub (e.g., [lapkt](https://github.com/AI-Planning/planutils/blob/main/planutils/packages/lapkt/install))  would do.

**Comment by haz** [comment]
Using the latest version of enhsp (@hstairs can let us know if that’s not wise), and disabling topk for now, until it works again from @ctpelok77 ’s side. Marking as resolved since the latest spins up again.

**Comment by hstairs** [comment]
I wanted to push a newer version, but I am not sure whether a aarch64 image is good with you guys. I think no

**Comment by haz** [comment]
Ya, likely needs to be amd. The existing enhsp hosted isn't updated?

**Comment by haz** [comment]
Beauty. And if it's located at docker://ctpelok77/delfi:latest , then there's nothing that need be done for planutils to update. May need a redeploy of the PaaS, but that will happen soon enough again with changes coming to the service.
