### ISSUE TITLE
New installation with `make` fails on source metadata -- add `DOCKER_BUILDKIT=0` to docs?

### ISSUE THREAD

**Issue by rpgoldman** [AI-Planning/planning-as-a-service#58]
At the end of the process started by `make`, I see this error message:

```
------
 > [worker internal] load metadata for docker.io/library/planutils:latest:
------
failed to solve: planutils:latest: failed to resolve source metadata for docker.io/library/planutils:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [Makefile:7: build-start] Error 17
```

I found an answer for this [on Stackexchange](https://stackoverflow.com/questions/73812700/docker-error-internal-load-metadata-for-docker-io) -- `DOCKER_BUILDKIT=0 make`

Maybe this should be added to the documentation?

But when I build this way I get:

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.
```

**Comment by haz** [comment]
I wasn't able to reproduce this. Are you able to fetch images in general? You can test access to the generic planutils docker (which this builds on) by running this:

```bash
docker pull aiplanning/planutils:latest
```

**Comment by rpgoldman** [comment]
That's not it:
```
$ docker pull aiplanning/planutils:latest
latest: Pulling from aiplanning/planutils
Digest: sha256:e2e1626f068f0d59dfb8d9a4cf0c4115e9208809f37ac8f44931b4a2daa75ad3
Status: Image is up to date for aiplanning/planutils:latest
docker.io/aiplanning/planutils:latest
```

Also, I was able to build and push some images for other projects yesterday from the same machine.

Is there any chance this could be because I'm running rootless docker? I'm just thinking of what could be different for me from you.

Or ... this couldn't be influenced by the contents of my `.env` file, could it? I think this is too early, but I could easily be wrong.

Another thing I'm doing differently: I am doing `make` in userspace not as root (`sudo make`): I don't have root privileges on this server. Forgot to mention that; sorry. Why is root required?

**Comment by rpgoldman** [comment]
I seem to have gotten past this issue by replacing `planutils:latest` with `aiplanning/planutils:latest` in the subsidiary `Dockerfile`'s

I wish I could say that I knew why this made a difference, but I do not.  Would you like a MR with this change?

At any rate, there's one more problem that seems clearly related to

**Comment by haz** [comment]
Hrmz...I don't think that's the right solution. What's conflating things here is that the root level docker file is built and named `planutils:latest` (in the make file). It's this custom build that the others use (having access to the custom planners installed). Is there any chance the broken build on the top-level docker file was cause `planutils:latest` to not be created, and thus causing an error in the rest of the build? It's #57 that needs fixing before that will work again.

**Comment by rpgoldman** [comment]
It looks like everything built correctly:
```
rpg@lacrosse-0:~/src/planning-as-a-service/server$ docker image list
REPOSITORY                                       TAG                   IMAGE ID       CREATED          SIZE
server_web                                       latest                ecd7a4e26044   46 minutes ago   801MB
server_worker                                    latest                e7648143297a   46 minutes ago   801MB
server_monitor                                   latest                32bd1cbc777f   46 minutes ago   801MB
server_frontend                                  latest                e2606ef0ed61   46 minutes ago   738MB
<none>                                           <none>                d70b72a3e9a3   3 days ago       2.13GB
<none>                                           <none>                2e9fc2472ef3   3 days ago       2.22GB
<none>                                           <none>                a806fd68f785   3 days ago       2.22GB
<none>                                           <none>                cb4c7d87a182   3 days ago       2.21GB
<none>                                           <none>                ebc581151829   3 days ago       2.22GB
planutils                                        latest                3b4bb3652d87   3 days ago       2.13GB
```
I just tried adding in `aiplanning/` because what I saw in the output was first:
```
=> => naming to docker.io/library/planutils:latest
```
and then
```
 > [web internal] load metadata for docker.io/library/planutils:latest:
------
failed to solve: planutils:latest: failed to resolve source metadata for docker.io/library/planutils:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
``` 
I was confused by the presence of `docker.io` in the image name, since this is a local-only image, isn't it? I confess, though, that I don't understand the naming convention here, neither why `docker.io` is used, nor `library`. Are those magic names for docker?

**Comment by rpgoldman** [comment]
Ok, I did some googling. I'm still confused about that `docker.io`: according to [this page](https://docs.docker.com/reference/cli/docker/image/tag/):
> If you don't specify a hostname, the command uses Docker's public registry at registry-1.docker.io by default. Note that docker.io is the canonical reference for Docker's public registry.

So, the canonical reference is `docker.io`, but they use `registry-1.docker.io` because ... they just like to be confusing? Anyway, seems like specifying `docker.io` should be fine.

Then `library/` is the default namespace, so that looks good too.

Is there any chance that the image is in my personal (i.e., rootless) docker image store, and is not being found because docker-compose specifies `privileged` context?  Or vice versa? Somehow the image is being written by root in the container?

So `aiplanning/planutils:latest` is the source image and `library/planutils:latest` is the derived (locally built) image.

**Comment by haz** [comment]
Aye, it's _meant_ to be a local one, but if it's failing to find it, then it'll look for the remote. I think the real test would be renaming it from `planutils:latest` in the top level make file, and sub-directory dockerfiles, to something like `localplanutils:latest` and see if it breaks at some place.

**Comment by haz** [comment]
This is where it's named: https://github.com/AI-Planning/planning-as-a-service/blob/main/server/Makefile#L4

The instructions say to run `sudo make`, but I think it may be for the `--privileged` running of the servers (though, your machine may be configured to run docker as root by default).

**Comment by rpgoldman** [comment]
Hm. Same error (with a new name):
```
failed to solve: localplanutils:latest: failed to resolve source metadata for docker.io/library/localplanutils:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Does this help at all:
```
rpg@lacrosse-0:~/src/planning-as-a-service/server$ docker image list localplanutils:latest
REPOSITORY       TAG       IMAGE ID       CREATED      SIZE
localplanutils   latest    3b4bb3652d87   3 days ago   2.13GB
rpg@lacrosse-0:~/src/planning-as-a-service/server$ docker image list docker.io/library/localplanutils:latest
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
```

**Comment by haz** [comment]
And `docker run -it localplanutils:latest` works?

**Comment by rpgoldman** [comment]
Yes, just checked and it runs properly.

These all work:
```
docker run -it localplanutils:latest
docker run -it library/localplanutils:latest
docker run -it docker.io/library/localplanutils:latest
```

I imagine that somehow the context that docker compose is running in is different, but no idea how to tell what that is...

**Comment by rpgoldman** [comment]
Another issue with running privileged containers is that the containers write files that are not owned by the userid running them.  Docker is great when it's great, but when it's not, it's horrid.

**Comment by haz** [comment]
So back to the original...

```bash
------
 > [worker internal] load metadata for docker.io/library/planutils:latest:
------
failed to solve: planutils:latest: failed to resolve source metadata for docker.io/library/planutils:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [Makefile:7: build-start] Error 17
```

Does this happen when it's trying to build the `worker` image or when it spins it up? I'm assuming the latter, since your `docker image list` shows `server_worker` successfully built in there.

**Comment by rpgoldman** [comment]
OK, I got it!!!!

I built everything with `DOCKER_BUILDKIT=0` but then I logged out and when I logged in again, I forgot to reestablish this. 🤦‍♂️ 

Looks like with that environment variable reestablished (this seems like a job for `.direnv`), the service starts properly!

**Comment by rpgoldman** [comment]
Yes, I can build and run with that variable but note:

1. I had to tweak the `docker-compose.yaml` file so I wasn't trying to use the host machine's port 80 and
2. I got grumpy messages about `DOCKER_BUILDKIT=0` being deprecated.  Since nowhere did I read an explanation (at least not one I could understand) about why setting that variable fixed my problem, I'm not sure what a fix is. Presumably it's doing something to make the build process compatible with buildx instead of doing what I did...

**Comment by haz** [comment]
Ya, I think we'll handle 1 when I put together a fix for #61 . This all stem from not being able to run it as root, ya?

@nirlipo : do you happen to recall any issues that led to [this](https://github.com/AI-Planning/planning-as-a-service/blob/main/README.md?plain=1#L38) requiring sudo?

**Comment by rpgoldman** [comment]
I'm not sure.  I don't understand why I had to set `DOCKER_BUILDKIT` to zero, so I don't know whether that's related to running in userspace or not.

**Comment by nirlipo** [comment]
I don't recall why we need sudo for docker compose commands. Note that since that makefile was created, [docker-compose became docker compose (v2)](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose), and we had to change some docker commands. I wonder if this is related at all.

What happens when you try to build and compose without sudo? 

PS: I may be slow responding, start of the semester down under :)

**Comment by rpgoldman** [comment]
> I don't recall why we need sudo for docker compose commands. Note that since that makefile was created, [docker-compose became docker compose (v2)](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose), and we had to change some docker commands. I wonder if this is related at all.
> 
> 
> 
> What happens when you try to build and compose without sudo? 
> 
> 
> 
> PS: I may be slow responding, start of the semester down under :)  

Looks like the only reason one needs root is to open or 80 on the host machine, based on my experience. 

Note that even though I'm not running  make as root, the containers are still running privileged

**Comment by haz** [comment]
Ah, right...I think it's coming back to me that 80 was specially reserved. I've been trying to work away at fixing several of the issues, and doing so while running without root. Partial progress over at #62 

> Note that even though I'm not running make as root, the containers are still running privileged

This likely comes down to the way docker is setup on the machine -- has admin access when invoked. Would also probably be the source of files created being owned by root.

Let's see if the new changes (once I'm done) doesn't address this issue for us. If not, we can document the symptom and detail the fix in the top-level README.

**Comment by rpgoldman** [comment]
> This likely comes down to the way docker is setup on the machine -- has admin access when invoked. Would also probably be the source of files created being owned by root.

Actually, I should have been more clear: it's down to the docker-compose file, which specifies that containers are to be run privileged.  See, for example https://github.com/AI-Planning/planning-as-a-service/blob/4cb5d2abbccacbcf3615a091876e7001c4abc8b1/server/docker-compose.yml#L4

**Comment by nirlipo** [comment]
Just to note that if you are using docker compose V2 you can have to drop the "-compatibility" flag from the Makefile. 

Now it all came back: we needed sudo to set up the private key for https, and port 80 is used to have the landing page https://solver.planning.domains/

@haz given that this is not really needed for Paas, should we remove the frontend altogether from the repo and keep it separately in the server? See the current services provided by it: https://github.com/AI-Planning/planning-as-a-service/blob/main/server/frontend/app.py

**Comment by haz** [comment]
I think it's alright to leave it in -- default port can be non-80, and then just reset it to 80 if you want an official deploy (or 443, if that's your jam ;)).

With the current main branch, I can spin it up easily without root.

@rpgoldman Can you confirm the status of this issue in the latest? (I.e., using the MySQL fix)

**Comment by rpgoldman** [comment]
Per our discussion, it all works now in rootless docker if I just don't try to get clever with the `user` attribute, which works differently in rootless because of the namespace rewriting.
