### ISSUE TITLE
monitor run failed

### ISSUE THREAD

**Issue by zutuanwang** [AI-Planning/planning-as-a-service#65]
run from docker
docker compose --compatibility up -d --build
monitor container start failed, below is error log:

`Traceback (most recent call last):
  File "/usr/local/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/usr/local/lib/python3.10/dist-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.10/dist-packages/celery/bin/base.py)`

**Comment by haz** [comment]
This should be resolved with the PR under review.

**Comment by rpgoldman** [comment]
@haz Running with your version the monitor starts successfully.

**Comment by haz** [comment]
Will keep this open until we get the PR in, then. Thanks for confirming!

**Comment by nirlipo** [comment]
Monitor should be running now. Note that by default the docker-compose file is set to run without https. #62 has been merged.

**Comment by haz** [comment]
Closing, as it should now be resolved.
